(DEFUN MULTIPLOSPRESENTES(L) (MULTIPLOS L L))

(DEFUN MULTIPLOS(L1 L2)
  (COND
   ((NULL L2) NIL)
   (T (APPEND (LISTAMULTIPLOS L1 (FIRST L2)) (MULTIPLOS L1 (REST L2))))))

(DEFUN LISTAMULTIPLOS (L N)
  (COND
   ((NULL L) NIL)
   ((AND (DIVISOR (FIRST L) N) (NOT (= (FIRST L) N))) (CONS (ParOrd N (FIRST L)) (LISTAMULTIPLOS (REST L) N)))
   (T (LISTAMULTIPLOS (REST L) N))))

(DEFUN ParOrd(N1 N2) (CONS N1 (CONS N2 NIL)))
(DEFUN DIVISOR(N1 N2) (= (MOD N1 N2) 0))