(DEFUN PREORDEN (A)
  (COND
   ((HOJA A) (CONS A NIL))
   ((NULL A) NIL)
   (T (CONS (RAIZ A) (APPEND (PREORDEN (HI A)) (PREORDEN(HD A)))))))

(DEFUN RAIZ (A) (FIRST (REST A)))
(DEFUN HI (A) (FIRST A))
(DEFUN HD (A) (FIRST (REST (REST A))))
(DEFUN HOJA(A)
  (COND
   ((LISTP A) NIL)
   (T T)))