


(DEFUN CODIGOS(L)
  (CONS
   ((NULL L) NIL)
   (T (CONS (CODIGO (FIRST L)) (CODIGOS (REST L))))))

(DEFUN ELIMREPETIDOS



(DEFUN LISTACOMPLETACODIGO(L COD) (CONS COD (LISTASCODIGO L COD)))

(DEFUN LISTASCODIGO (L COD)
  (COND
   ((NULL L) NIL)
   ((= (CODIGO (FIRST L)) COD) (APPEND (REST  L) (LISTACODIGO (REST L) COD)))
   (T (LISTACODIGO (REST L) COD))))

(DEFUN CODIGO(L) (FIRST L))