(DEFUN INTERCALAR (L1 L2)
  (COND
   ((NULL L1) L2)
   ((NULL L2) L1)
   ((< (FIRST L1) (FIRST L2)) (CONS (FIRST L1) (INTERCALAR L2 (REST L1))))
   (T (CONS (FIRST L2) (INTERCALAR L1 (REST L2))))))