(DEFUN LISTALINEAL(L) (APLANARLISTA L))

(DEFUN APLANARLISTA(L)
  (COND
   ((NULL L) NIL)
   ((ATOM (FIRST L)) (CONS (FIRST L) (APLANARLISTA (REST L))))
   (T (CONCATENAR (APLANARLISTA (FIRST L)) (APLANARLISTA (REST L))))))

(DEFUN CONCATENAR(N L)
  (COND
   ((NUMBERP N) (CONS N L))
   (T (APPEND N L))))
