(DEFUN CANTCONSL (L) (+ 1 (CANTIDADSUBLISTAS L)))

(DEFUN CANTIDADSUBLISTAS(L)
  (COND 
   ((NULL L) 0)
   ((LISTP (FIRST L)) (+ 1 (CANTIDADSUBLISTAS (FIRST L)) (CANTIDADSUBLISTAS (REST L))))
   (T (CANTIDADSUBLISTAS (REST L)))))