(DEFUN ELIMrepADYACENTES(L)
  (COND
   ((NULL L) NIL)
   (T (CONS (FIRST L) (ELIMrepADYACENTES (ELIMADYACENTES (REST L) (FIRST L)))))))

(DEFUN ELIMADYACENTES(L N)
  (COND
   ((NULL L) NIL)
   ((= (FIRST L) N) (ELIMADYACENTES (REST L) N))
   (T L)))