(DEFUN CANTIDADNUMEROS(L) (CANTIDADNUM (APLANARLISTA L)))

(DEFUN CONCATENAR(N L)
  (COND
   ((NUMBERP N) (CONS N L))
   (T (APPEND N L))))

(DEFUN APLANARLISTA(L)
  (COND
   ((NULL L) NIL)
   ((ATOM (FIRST L)) (CONS (FIRST L) (APLANARLISTA (REST L))))
   (T (CONCATENAR (APLANARLISTA (FIRST L)) (APLANARLISTA (REST L))))))

(DEFUN CANTIDADNUM (L)
  (COND
  ((NULL L) 0)
  ((NUMBERP(FIRST L)) (+ 1 (CANTIDAD (REST L))))
  (T (CANTIDAD (REST L)))))