(DEFUN LISTANPRIMOS(I) (NUMEROSPRIMOS I 2))

(DEFUN NUMEROSPRIMOS(I N)
  (COND 
   ((= I 0) NIL)
   ((PRIMO N) (CONS N (NUMEROSPRIMOS (- I 1) (+ N 1))))
   (T (NUMEROSPRIMOS I (+ N 1)))))

(DEFUN PRIMO(N) (NOT (TIENEDIVISORES N 2 (- N 1))))

(DEFUN TIENEDIVISORES(N D H)
  (COND
   ((> D H) NIL)
   ((DIVISOR N D) T)
   (T (TIENEDIVISORES N (+ D 1) H))))

(DEFUN DIVISOR(N D)
  (COND
  ((= (MOD N D) 0) T)
  (T NIL)))
