(DEFUN LISTAPAL(L)
  (COND
   ((NULL L) T)
   ((NULL (REST L)) T)
   ((EQUAL (FIRST L) (ULTIMO L)) (LISTAPAL (RESTLAST (REST L))))
   (T NIL)))

(DEFUN RESTLAST(L)
  (COND
   ((NULL L) L)
   ((NULL (REST L)) NIL)
   (T (CONS (FIRST L) (RESTLAST (REST L))))))

(DEFUN ULTIMO(L) (FIRST (LAST L)))
